In [1]:
import pandas as pd
import numpy as np
import glob
import os

In [28]:
c = np.diag(np.random.randn(10,))

In [83]:
a = np.random.randn(10,20) #10个样本，20个组分

array([[-0.7718897 ,  0.40894122, -0.66395459,  0.74349265,  0.37151965,
        -0.53131088, -0.26622435,  1.22679663, -0.92132766,  0.36683612,
         0.90792269, -0.5561285 ,  1.04176995, -0.51271148, -1.00985685,
        -0.39497697, -1.47077339,  0.09306963, -0.95224428,  0.27643105],
       [ 0.54999788,  0.02936634,  0.1041145 , -0.69575209,  0.13404809,
        -1.60664877,  0.50949091,  0.27899077,  1.55490515,  1.32289526,
        -1.95202533,  0.40299383,  0.27679592,  1.16043608, -0.29528798,
        -0.19541588, -0.13316736,  0.54861781, -0.15656827, -0.47037661],
       [-0.42210492, -1.34734457, -1.5461121 ,  1.19571826, -0.65580438,
        -1.4091347 ,  1.67055141, -0.24773935,  1.96474165, -0.27765444,
        -1.18651985,  0.17444068,  1.0298039 ,  0.52913233, -2.80726561,
        -0.42824716, -1.26423082,  0.92140315, -0.062955  ,  0.62277714],
       [ 1.15768451, -0.01876553,  0.02849132,  2.22700897,  1.04379931,
        -1.85754554,  0.60025944,  0.76286232,  

In [79]:
w = np.random.randn(20,10)#20个组分，10个属性,

In [77]:
Pw = np.random.randn(10) #每个属性的权重Pw

In [91]:
s=a*w.dot(Pw)
s.shape

(10, 20)

In [41]:
c.dot(w)

array([[ 0.03182381,  0.5366284 ],
       [-1.01943418, -0.1684098 ],
       [ 0.39357045,  0.30604706],
       [-1.90640518, -0.00660601],
       [ 1.35358605,  1.73055968],
       [-0.85357614,  0.52656621],
       [ 0.44240537, -1.36129895],
       [ 0.22365257, -0.10572088],
       [-0.60936265, -0.56696292],
       [-0.30409895,  0.02450244]])

In [46]:
c.dot(w).dot(Pws)

array([ 0.03182381, -1.01943418,  0.39357045, -1.90640518,  1.35358605,
       -0.85357614,  0.44240537,  0.22365257, -0.60936265, -0.30409895])

In [2]:
# 工作路径- 文件存放的文件夹
tests = pd.read_excel('./tests.xlsx') #读表
properties = pd.read_excel('./properties.xlsx')

In [3]:
path =r'./tests' #存放tests的文件夹
allFiles = glob.glob(path + "/*.xlsx")
parts = pd.DataFrame()
list_ = []
for file_ in allFiles:
    df = pd.read_excel(file_,index_col=0, header=0)
    list_.append(df)
parts = pd.concat(list_,axis=1)
parts.columns = list(map(lambda x:x[len(path+'/'):-len('.xlsx')],allFiles))
parts.fillna(0,inplace=True)

In [4]:
parts.to_csv('./parts.xls')

In [5]:
parts

方向盘  方向盘1  方向盘2  方向盘3   顶棚  顶棚2
A  0.0   0.0   0.0   0.0  0.0  2.0
C  0.3   0.3   0.3   0.3  2.0  2.0
D  0.4   0.0   0.0   1.0  0.0  0.0
E  0.2   0.2   0.2   0.2  0.0  0.0
G  0.0   0.0   0.0   0.0  5.0  5.0
M  0.0   0.0   0.0   0.0  4.0  4.0
S  0.0   0.2   0.2   0.2  1.0  1.0
W  0.0   0.0   2.0   2.0  0.0  0.0

不同部位的空气得分Y?

In [6]:
scores = pd.read_excel('./scores.xlsx',index_col=0)

In [7]:
scores

得分
部位      
方向盘   50
顶棚    60
方向盘1  51
方向盘2  52
顶棚1   20
顶棚2   30
方向盘3  55

# 最小二乘拟合
~~~
parts*w = scores
w = np.linalg.pinv(parts.dot(parts.T)).dot(parts.dot(scores))
~~~

In [8]:
w = np.linalg.pinv(parts.dot(parts.T)).dot(parts.dot(scores))

ValueError: matrices are not aligned

实验测试数据表tests.xlsx格式：
- 从A1开始
- 第一行表头
- 每行为一个样本的测试结果:各成分浓度
- 每列为一个成分的浓度，没有则为0
---
化合物属性信息表properties.xlsx格式：
- 从A1开始
- 第一行表头
- 每行为一个化合物的属性信息
- 每列为一种属性值

In [ ]:
def avg_properties(tests, properties):
    #样品浓度-->样本属性
    
    tests.set_index(tests.columns[0],inplace=True)
    properties.set_index(properties.columns[0],inplace=True)
    properties = properties.loc[tests.columns,:]
    tests = tests.T/tests.T.sum()
    results = tests.T.dot(properties)
    return results

In [ ]:
results = avg_properties(tests, properties)
tofile = './results_tests.xls'
results.to_excel(tofile) #写入数据到results_tests.xls

最终结果为results_tests.xls：
- 每行为一个样本的属性值

In [ ]:
properties

In [ ]:
tests

In [ ]:
results

In [ ]:
np.random.randn(10,1)